### ISSUE TITLE
Are the trained weights available?

### ISSUE THREAD

**Issue by IcedDoggie** [vivoutlaw/SSIAM#1]
I browsed through but only could find the trained features instead of weights. are the weights available somewhere? i am planning to get the weights to convert it into pytorch.

**Comment by vivoutlaw** [comment]
hi, here is the dataset: https://cvhci.anthropomatik.kit.edu/~datasets-publisher/published_datasets/face_and_body/BBT_Buffy_ACCIO_VGG_face_reps/VGG2.tar.gz
